import { createRouter, createWebHistory } from 'vue-router'

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes: [
    {
      path:"",
      component:()=>import("@/views/index.vue"),
      children:([
        {
          path:"",
          component:()=>import("@/views/Home/home.vue")
        },
        {
          path:"/home",
          component:()=>import("@/views/Home/home.vue")
        },
        {
          path:"/quote",
          component:()=>import("@/views/Quotes/quotes.vue"),
          children:[
            {
              path:"",
              component:()=>import("@/views/Quotes/components/optional.vue")
            },
            {
              path:"/optional",
              component:()=>import("@/views/Quotes/components/optional.vue")
            },
            {
              path:"/usdt",
              component:()=>import("@/views/Quotes/components/usdt.vue")
            }
          ]
        },
        {
          path:"/mine",
          component:()=>import("@/views/Mine/mine.vue")
        },
        {
          path:"/wallet",
          component:()=>import("@/views/Wallet/wallet.vue"),
          children:[
            {
              path:"",
              component:()=>import("@/views/Wallet/components/coins.vue")
            },
            {
              path:"/coins",
              component:()=>import("@/views/Wallet/components/coins.vue")
            },
            {
              path:"/contract",
              component:()=>import("@/views/Wallet/components/contract.vue")
            },
            {
              path:"/fait",
              component:()=>import("@/views/Wallet/components/fait.vue")
            },
            {
              path:"/second",
              component:()=>import("@/views/Wallet/components/second.vue"
              )
            }
          ]
        }
      ])
    },
    {
      path:"/login",
      component:()=>import("@/views/Login/login.vue")
    },
    {
      path:"/register",
      component:()=>import("@/views/Register/register.vue")
    },
    {
      path:"/order",
      component:()=>import("@/views/Order/order.vue"),
      children:[
        {
          path:"",
          component:()=>import("@/views/Order/components/buy.vue")
        },
        {
          path:"/buy",
          component:()=>import("@/views/Order/components/buy.vue")
        },
        {
          path:"/sell",
          component:()=>import("@/views/Order/components/sell.vue")
        }
      ]
    }
  ]
})

export default router
